### ISSUE TITLE
What happened to attributes?

### ISSUE THREAD

**Issue by flybrys** [caronc/ha-ultrasync#21] opened 2022-06-04 08:20 UTC
I had a bunch of automations using the attributes from the Area 1 State entity. Now all entities attributes seems to be missing. 
Any way they can be fixed?

**Comment by caronc** [comment] 2022-06-04 10:33
Nothing was touched in the code base for a very long time now. Did you recently update your version of home assistant?

**Comment by brywithawhy** [comment] 2022-06-04 10:41
I update it every month with the new releases however do read the breaking changes thoroughly. I don't recall seeing anything that would affect it however it could be the cause.
Will the integration support newer versions of HA?

**Comment by caronc** [comment] 2022-06-04 11:04
I'm just trying to isolate the cause. There we report earlier of something being deprecated showing up in the logs a couple of releases ago. Likely this deprecation went through in the last update. 

I haven't updated in a while, so i haven't seen this.

Unfortunately there is always a possibility that things in Home Assistant will change and break community plugins like your experiencing.

Would you be able to roll back your last update of HA? That would restore your service at least.

As per this software being future proof, this might be a bit trickier. Would love any help from the community on this one.

**Comment by brywithawhy** [comment] 2022-06-04 11:26
I'm using a few of the newer features so can't really roll back.
It's not mission critical for me but has been super handy. My team also use it for our business, so I'm willing to contribute some $$ if someone can get it up to date

**Comment by stefdewilde** [comment] 2022-07-01 13:49
These issue should be fixed. I also had the same issue, but with one of the updates that happened it got solved I think.

Is it possible to add a version number to the integration? Would be easier to follow up everything aswell :)

**Comment by caronc** [comment] 2022-07-01 13:59
Valid point @stefdewilde ; i just created a tag and a release [here](https://github.com/caronc/ha-ultrasync/releases/tag/v1.0.0)

**Closed** 2024-06-22 08:19 UTC
